### PR TITLE
Update glibc on AT 15.0

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 52d011974318

### CODE REVIEW

**Comment by rzinsly** [comment]
1 Python test failed on  RHEL8:
```
0:01:28 load avg: 4.61 [268/395/1] test_eintr failed (1 failure) (1 min 6 sec)
test test_eintr failed -- Traceback (most recent call last):
  File "/home/tcbot/bot-slave/at_opt/at15.0/lib64/python3.9/test/test_eintr.py", line 33, in test_all
    script_helper.assert_python_ok("-u", tester, "-v")
  File "/home/tcbot/bot-slave/at_opt/at15.0/lib64/python3.9/test/support/script_helper.py", line 156, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "/home/tcbot/bot-slave/at_opt/at15.0/lib64/python3.9/test/support/script_helper.py", line 142, in _assert_python
    res.fail(cmd_line)
  File "/home/tcbot/bot-slave/at_opt/at15.0/lib64/python3.9/test/support/script_helper.py", line 70, in fail
    raise AssertionError("Process return code is %d\n"
AssertionError: Process return code is 1
command line: ['/home/tcbot/bot-slave/at_opt/at15.0/bin/python3', '-X', 'faulthandler', '-I', '-u', '/home/tcbot/bot-slave/at_opt/at15.0/lib64/python3.9/test/eintrdata/eintr_tester.py', '-v']
stdout:
---
---
stderr:
---
test_flock (__main__.FNTLEINTRTest) ... ERROR
test_lockf (__main__.FNTLEINTRTest) ... ok
test_read (__main__.OSEINTRTest) ... ok
test_wait (__main__.OSEINTRTest) ... ok
test_wait3 (__main__.OSEINTRTest) ... ok
test_wait4 (__main__.OSEINTRTest) ... ok
test_waitpid (__main__.OSEINTRTest) ... ok
test_write (__main__.OSEINTRTest) ... ok
test_devpoll (__main__.SelectEINTRTest) ... skipped 'need select.devpoll'
test_epoll (__main__.SelectEINTRTest) ... ok
test_kqueue (__main__.SelectEINTRTest) ... skipped 'need select.kqueue'
test_poll (__main__.SelectEINTRTest) ... ok
test_select (__main__.SelectEINTRTest) ... ok
test_sigtimedwait (__main__.SignalEINTRTest) ... ok
test_sigwaitinfo (__main__.SignalEINTRTest) ... ok
test_accept (__main__.SocketEINTRTest) ... ok
test_open (__main__.SocketEINTRTest) ... ok
test_os_open (__main__.SocketEINTRTest) ... ok
test_recv (__main__.SocketEINTRTest) ... ok
test_recvmsg (__main__.SocketEINTRTest) ... ok
test_send (__main__.SocketEINTRTest) ... ok
test_sendall (__main__.SocketEINTRTest) ... ok
test_sendmsg (__main__.SocketEINTRTest) ... ok
test_sleep (__main__.TimeEINTRTest) ... ok
======================================================================
ERROR: test_flock (__main__.FNTLEINTRTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tcbot/bot-slave/at_opt/at15.0/lib64/python3.9/test/eintrdata/eintr_tester.py", line 525, in test_flock
    self._lock(fcntl.flock, "flock")
  File "/home/tcbot/bot-slave/at_opt/at15.0/lib64/python3.9/test/eintrdata/eintr_tester.py", line 502, in _lock
    raise Exception("failed to sync child in %.1f sec" % dt)
Exception: failed to sync child in 60.0 sec
----------------------------------------------------------------------
Ran 24 tests in 66.720s
FAILED (errors=1, skipped=2)
---
```

**Comment by mscastanho** [comment]
This issue is most likely unrelated to the changes, as we have seen it before (#1873). I restarted the failing build to confirm.

**Comment by rzinsly** [comment]
The new build failed Python's `test_subprocess` with a timeout error, it is likely to be related to #2368.

**Comment by rzinsly** [comment]
> We have seen this issue with other PRs as well, it's been happening only on our RHEL8 host. So I believe this is likely unrelated to this change.
> 
> I also built AT using this PR on RHEL8 and ran `test_eintr` 100 times without a single failure. I think we should merge this PR as-is.
> 
> @rzinsly do you agree?

Yes!

**Pull request merged**
