### PR TITLE
Update glibc on AT 14.0

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 04bba1e5d84b

### CODE REVIEW

**Comment by mscastanho** [comment]
Same as #1659

binutils stage 2:
```
/home/tcbot/bot-slave/at/src/at14.0-0.redhat-8_ppc64le_ppc64le/sources/binutils/gold/main.cc: In function ‘int main(int, char**)’:
/home/tcbot/bot-slave/at/src/at14.0-0.redhat-8_ppc64le_ppc64le/sources/binutils/gold/main.cc:294:36: error: ‘mallinfo mallinfo()’ is deprecated [-Werror=deprecated-declarations]
  294 |       struct mallinfo m = mallinfo();
      |                                    ^
In file included from /home/tcbot/bot-slave/at/src/at14.0-0.redhat-8_ppc64le_ppc64le/sources/binutils/gold/main.cc:29:
/home/tcbot/bot-slave/at_opt/at14.0/include/malloc.h:118:24: note: declared here
  118 | extern struct mallinfo mallinfo (void) __THROW __MALLOC_DEPRECATED;
      |                        ^~~~~~~~
```

**Comment by mscastanho** [comment]
@er-1 isn't AT 14 supposed to follow 2.32 release? The commit that caused this issue was pushed only to master a few days ago, and was not backported to 2.32 branch. Am I missing something?

**Comment by er-1** [comment]
> @er-1 isn't AT 14 supposed to follow 2.32 release? The commit that caused this issue was pushed only to master a few days ago, and was not backported to 2.32 branch. Am I missing something?

@mscastanho Thx for noticing this.
You are right. AT 14.0 is supposed to track 2.32 branch. But https://github.com/advancetoolchain/advance-toolchain/blob/master/scripts/utilities/update_revision.sh didn't handle well multiple branches names, and it put back AT 14.0 on glibc master.
I'll send a PR to fix that.

**Comment by mscastanho** [comment]
@er-1 Nice, thanks! So I guess we can close this now.

**Pull request closed without merging**
