### PR TITLE
Diverge python on AT next from 14.0

### PR DESCRIPTION
**Pull request by er-1**
python 3.9.0 has been released and will be tracked on AT next.
AT 14.0 will continue to track python 3.8 branch.

### CODE REVIEW

**Review by mscastanho — CHANGES_REQUESTED** [review]
@er-1 The build failed to apply patches to Python. Maybe we have to change some of then to apply cleanly to this new version?

Also, I noticed that the preparation commit that should simply break the symlink and copy the config from 14.0 to next is actually changing more things. Was it intentional? AFAIU the command below shouldn't show anything, because the files should be equal.

```diff
$ git diff 8ac7674186ce:configs/14.0/packages/python/sources 8ac7674186ce:configs/next/packages/python/sources 
diff --git a/configs/14.0/packages/python/sources b/configs/next/packages/python/sources
index 924a6ff..b4b5477 100644
--- a/configs/14.0/packages/python/sources
+++ b/configs/next/packages/python/sources
@@ -20,10 +20,10 @@
 #
 
 ATSRC_PACKAGE_NAME="Python"
-ATSRC_PACKAGE_VER=3.8.6
-ATSRC_PACKAGE_REV=8f7eab788aed
+ATSRC_PACKAGE_VER=3.8.5
+ATSRC_PACKAGE_REV=838316db08a8
 ATSRC_PACKAGE_LICENSE="Python Software Foundation License 2"
-ATSRC_PACKAGE_DOCLINK="https://docs.python.org/${ATSRC_PACKAGE_VER%\.*}/"
+ATSRC_PACKAGE_DOCLINK="https://docs.python.org/${ATSRC_PACKAGE_VER}/"
 ATSRC_PACKAGE_RELFIXES=
 ATSRC_PACKAGE_STR_VER="${ATSRC_PACKAGE_NAME} ${ATSRC_PACKAGE_VER}"
 ATSRC_PACKAGE_VERID="${ATSRC_PACKAGE_VER}${ATSRC_PACKAGE_REV:+-${ATSRC_PACKAGE_REV}}"
@@ -54,11 +54,6 @@ atsrc_get_patches ()
                https://raw.githubusercontent.com/powertechpreview/powertechpreview/89d1d3cb24e43f8ec716e1047f8d94702b131fda/Python%20Fixes/python-3.6.3-skip_test_random_fork.patch \
                b6713b5bea7d419b18b8f8319ba5a6f2 || return ${?}
 
-       # Increase a timeout in test_subprocess.
-       at_get_patch \
-               https://raw.githubusercontent.com/powertechpreview/powertechpreview/ec0f7202f72ca7b946525b29aca58ec50979906e/Python%20Fixes/python-3.6.12-timeout-test_subprocess.patch \
-               a50e89dca0c51249be26f027a0474a23 || return ${?}
-
        # Disable zlib version check (test_zlib).
        at_get_patch \
                https://raw.githubusercontent.com/powertechpreview/powertechpreview/1fa3a5896a6ce15e8b85fcf24109db5c1ea5548a/Python%20Fixes/python-3.7-disable-zlib-version-check.patch \
@@ -71,7 +66,6 @@ atsrc_apply_patches ()
 {
        patch -p1 < python-3.8-getlib64.patch || return ${?}
        patch -p1 < python-3.7-disable-zlib-version-check.patch || return ${?}
-       patch -p1 < python-3.6.12-timeout-test_subprocess.patch || return ${?}
        patch -p1 < python-3.6.3-skip_test_random_fork.patch || return ${?}
 }
```

**Comment by er-1** [comment]
> @er-1 The build failed to apply patches to Python. Maybe we have to change some of them to apply cleanly to this new version?

@mscastanho right.

> Also, I noticed that the preparation commit that should simply break the symlink and copy the config from 14.0 to next is actually changing more things. Was it intentional? AFAIU the command below shouldn't show anything, because the files should be equal.

Outchy! This is bad. I prepared this patch a long time ago, I didn't check that.

**Comment by er-1** [comment]
I fixed the preparation commit (thanks to @mscastanho) knowing the patches won't apply.

**Comment by mscastanho** [comment]
The preparation commit looks good now, thanks @er-1

**Comment by mscastanho** [comment]
@er-1 let me know if you need help adapting the Python patches to the newer version.

**Comment by er-1** [comment]
> @er-1 let me know if you need help adapting the Python patches to the newer version.

@mscastanho I'd be glad if you can help.
I'm wondering if this PR shouldn't be done again from scratch. It has an AT 12.0 related commit (why I did that?), and the python revision needs an update.

**Pull request closed without merging**
