### PR TITLE
Update gcc on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 07d8961c723a

### CODE REVIEW

**Comment by tuliom** [comment]
Binutils build failed because GCC is catching a new error:

```
/home/tcbot/bot-slave/at/src/at12.0-0-alpha.suse-12_ppc64le_ppc64le/sources/binutils/bfd/elf64-ppc.c
: In function ‘ppc64_elf_write_core_note’:
/home/tcbot/bot-slave/at/src/at12.0-0-alpha.suse-12_ppc64le_ppc64le/sources/binutils/bfd/elf64-ppc.c
:2994:2: error: ‘strncpy’ specified bound 80 equals destination size [-Werror=stringop-truncation]
  strncpy (data + 56, va_arg (ap, const char *), 80);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
/home/tcbot/bot-slave/at/src/at12.0-0-alpha.suse-12_ppc64le_ppc64le/sources/binutils/bfd/elf.c: In f
unction ‘elfcore_write_prpsinfo’:
/home/tcbot/bot-slave/at/src/at12.0-0-alpha.suse-12_ppc64le_ppc64le/sources/binutils/bfd/elf.c:10462
:7: error: ‘strncpy’ specified bound 16 equals destination size [-Werror=stringop-truncation]
       strncpy (data.pr_fname, fname, sizeof (data.pr_fname));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tcbot/bot-slave/at/src/at12.0-0-alpha.suse-12_ppc64le_ppc64le/sources/binutils/bfd/elf.c:10463
:7: error: ‘strncpy’ specified bound 80 equals destination size [-Werror=stringop-truncation]
       strncpy (data.pr_psargs, psargs, sizeof (data.pr_psargs));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tuliom** [comment]
Usually, I'd suggest to wait for a Binutils fix before merging this patch.
However, I'm afraid GCC on AT next is outdated.  So, we should consider to add `-Wno-error=stringop-truncation` to binutils stage 2 and merge this patch.
We can remove that later when Binutils does fix the warnings.

**Comment by tuliom** [comment]
By the way, this is the kind of problem that may affect many packages...

**Comment by tuliom** [comment]
I've just noticed that Binutils is also outdated on AT next (commit from Nov. 20 2017).
There have already been some fixes for these issue, but I don't think [they fixed all of them](https://sourceware.org/git/?p=binutils-gdb.git&a=search&h=HEAD&st=commit&s=stringop-truncation).
Anyway, we should update Binutils before trying to use `-Wno-error=stringop-truncation` with this patch.

**Comment by rzinsly** [comment]
I'm closing this PR, let's work with the current revision if it still fails.

**Pull request closed without merging**
