### PR TITLE
Update gcc on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 69c426b89579

### CODE REVIEW

**Comment by mscastanho** [comment]
Binutils stage 2 failed with several instances of the following error:
```
In file included from /home/tcbot/bot-worker/at/src/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/sources/binutils/gold/mips.cc:46:
/home/tcbot/bot-worker/at/src/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/sources/binutils/gold/gc.h: In instantiation of ‘void gold::gc_process_relocs(gold::Symbol_table*, gold::Layout*, Target_type*, gold::Sized_relobj_file<size, big_endian>*, unsigned int, const unsigned char*, size_t, gold::Output_section*, bool, size_t, const unsigned char*) [with int size = 64; bool big_endian = false; Target_type = {anonymous}::Target_mips<64, false>; Scan = {anonymous}::Target_mips<64, false>::Scan; Classify_reloc = {anonymous}::Mips_classify_reloc<4, 64, false>; size_t = long unsigned int]’:
/home/tcbot/bot-worker/at/src/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/sources/binutils/gold/mips.cc:8731:76:   required from ‘void {anonymous}::Target_mips<size, big_endian>::gc_process_relocs(gold::Symbol_table*, gold::Layout*, gold::Sized_relobj_file<size, big_endian>*, unsigned int, unsigned int, const unsigned char*, size_t, gold::Output_section*, bool, size_t, const unsigned char*) [with int size = 64; bool big_endian = false; size_t = long unsigned int]’
/home/tcbot/bot-worker/at/src/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/sources/binutils/gold/mips.cc:8693:1:   required from here
/home/tcbot/bot-worker/at/src/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/sources/binutils/gold/gc.h:250:37: error: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second: [-Werror]
  250 |                 (*secvec).push_back(Section_id(NULL, 0));
      |                                     ^~~~~~~~~~~~~~~~~~~
```
This was probably by the deprecation of some std_pair construction patterns on gcc:
```
commit d96db15967e78d7cecea3b1cf3169ceb924678ac
Author: Jonathan Wakely <jwakely@redhat.com>
Date:   Wed Apr 28 17:46:01 2021 +0100

    libstdc++: Deprecate non-standard std::pair constructors [PR 99957]
```
Related GCC PR: [link|https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99957].

I'm investigating if there is an easy fix for this on the binutils side.

**Comment by er-1** [comment]
This might be fixed by #2110

**Comment by mscastanho** [comment]
@er-1 I don't think so, unfortunately. Checking the latest binutils code, the lines causing the issues are still there. And there were no changes to gold on the latest commits integrated into binutils by #2110.

But I think the fix is not that complex. I'm testing one now.

**Comment by mscastanho** [comment]
Upstream binutils bug created: [link](https://sourceware.org/bugzilla/show_bug.cgi?id=27815)

**Comment by mscastanho** [comment]
A fix has been merged upstream. I'll create a new PR against the current binutils to test the fix.

**Pull request closed without merging**
