### PR TITLE
Update binutils on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 72c03e30ae78

### CODE REVIEW

**Comment by er-1** [comment]
ck_gold failed:
```
ck_gold: power8:  Start logging...
ck_gold: power8:  Checking if binutils has been built with the gold linker...
ck_gold: power8:  Testing 64 bit gold linking...
ck_gold: power8:  Unrecognized error: /home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/../lib64/crt1.o: plugin needed to handle lto object
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/../lib64/crti.o: plugin needed to handle lto object
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/gcc/powerpc64le-linux-gnu/10.0.0/crtbegin.o: plugin needed to handle lto object
/tmp/ccpaX0dG.o: plugin needed to handle lto object
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib64/libc_nonshared.a(elf-init.oS): plugin needed to handle lto object
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/gcc/powerpc64le-linux-gnu/10.0.0/crtend.o: plugin needed to handle lto object
```
gccgo failed:
```
gccgo: power8:  Start logging...
gccgo: power8:  Running gccgo tests...
gccgo: power8:  Test if libgo.so supports split-stack...
gccgo: power8:  Test if all 32-bit go libraries were removed...
gccgo: power8:  Compiling with: /home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/bin/gccgo...
gccgo: power8:  Unrecognized error: /home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/../lib64/crt1.o: plugin needed to handle lto object
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/../lib64/crti.o: plugin needed to handle lto object
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/gcc/powerpc64le-linux-gnu/10.0.0/crtbegin.o: plugin needed to handle lto object
/tmp/cclN8314.o: plugin needed to handle lto object
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib64/libgobegin.a(libgobegin_a-go-main.o): plugin needed to handle lto object
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/gcc/powerpc64le-linux-gnu/10.0.0/libgcc.a(morestack.o): plugin needed to handle lto object
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/gcc/powerpc64le-linux-gnu/10.0.0/libgcc.a(generic-morestack.o): plugin needed to handle lto object
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib64/libc_nonshared.a(elf-init.oS): plugin needed to handle lto object
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/gcc/powerpc64le-linux-gnu/10.0.0/crtend.o: plugin needed to handle lto object
```

**Comment by er-1** [comment]
Same errors with revision 37606e67df76 (Aug, 26th).

**Comment by er-1** [comment]
Same errors with revision 217d2eaa69c2 (Sept, 2nd).

**Comment by er-1** [comment]
Same errors with revision 60391a255b72 (Sept, 9nd).

**Comment by er-1** [comment]
Same errors with revision f2f24aa9c438 (Sept, 17th).

**Comment by tuliom** [comment]
Alan Modra has just sent a patch that might fix this issue:
https://sourceware.org/ml/binutils/2019-09/msg00166.html

**Comment by er-1** [comment]
> Alan Modra has just sent a patch that might fix this issue:
> https://sourceware.org/ml/binutils/2019-09/msg00166.html

I ran a local build. The tests passed.

I'm closing this PR, so cherbot will make a new one taking the latest binutils commit (including the Alan Modra's fix).

**Pull request closed without merging**
