### PR TITLE
Update openssl on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 22623e0cc26a

### CODE REVIEW

**Comment by er-1** [comment]
2 python tests failed: test_ssl and test_urllib2_localnet.

**Comment by mscastanho** [comment]
`test_urllib2_localnet` fails with:
```
======================================================================                                                                            
ERROR: test_https (test.test_urllib2_localnet.TestUrlopen)                                                                                        
----------------------------------------------------------------------                                                                            
Traceback (most recent call last):                                                                                                                
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/test/test_urllib2_localnet.py", line 560, in test_https             
    data = self.urlopen("https://localhost:%s/bizarre" % handler.port, context=context)                                                           
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/test/test_urllib2_localnet.py", line 464, in urlopen                
    l.extend(f.readlines(200))                                                                                                                    
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/http/client.py", line 677, in readline                              
    result = self.fp.readline(limit)                                                                                                              
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/socket.py", line 589, in readinto                                   
    return self._sock.recv_into(b)                                                                                                                
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/ssl.py", line 1071, in recv_into                                    
    return self.read(nbytes, buffer)                                                                                                              
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/ssl.py", line 929, in read                                          
    return self._sslobj.read(len, buffer)                                                                                                         
ssl.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:2555)                                                                    
                                                                                                                                                  
======================================================================                                                                            
ERROR: test_https_sni (test.test_urllib2_localnet.TestUrlopen)
----------------------------------------------------------------------                                                                   [13/1808]
Traceback (most recent call last):                                                                                                                
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/test/test_urllib2_localnet.py", line 601, in test_https_sni         
    self.urlopen("https://localhost:%s" % handler.port, context=context)                                                                          
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/test/test_urllib2_localnet.py", line 464, in urlopen                
    l.extend(f.readlines(200))                                                                                                                    
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/http/client.py", line 677, in readline                              
    result = self.fp.readline(limit)                                                                                                              
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/socket.py", line 589, in readinto                                   
    return self._sock.recv_into(b)                                                                                                                
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/ssl.py", line 1071, in recv_into                                    
    return self.read(nbytes, buffer)                                                                                                              
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/ssl.py", line 929, in read                                          
    return self._sslobj.read(len, buffer)                                                                                                         
ssl.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:2555)

======================================================================
ERROR: test_https_with_cafile (test.test_urllib2_localnet.TestUrlopen)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/test/test_urllib2_localnet.py", line 568, in test_https_with_cafile
    cafile=CERT_localhost)
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/test/test_urllib2_localnet.py", line 464, in urlopen
    l.extend(f.readlines(200))
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/http/client.py", line 677, in readline
    result = self.fp.readline(limit)
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/home/mscastanho/AT/next-bug/opt/at-next-14.0-0-alpha/lib64/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:2555)

----------------------------------------------------------------------                                                                            
                                                                                                                                                  
Ran 21 tests in 2.004s                                                                                                                            
                                                                                                                                                  
FAILED (errors=3)                                                                                                                                 
test test_urllib2_localnet failed                                                                                                                 
test_urllib2_localnet failed                                                                                                                      
                                                                                                                                                  
== Tests result: FAILURE ==                                                                                                                       
                                                                                                                                                  
1 test failed:                                                                                                                                    
    test_urllib2_localnet                                                                                                                         
                                                                                                                                                  
Total duration: 2.1 sec                                                                                                                           
Tests result: FAILURE
```
I suspect this has to do with this openssl patch:
```
commit db943f43a60d1b5b1277e4b5317e8f288e7a0a3a
Author: Matt Caswell <matt@openssl.org>
Date:   Fri Jan 17 17:39:19 2020 +0000

    Detect EOF while reading in libssl
    
    If we hit an EOF while reading in libssl then we will report an error
    back to the application (SSL_ERROR_SYSCALL) but errno will be 0. We add
    an error to the stack (which means we instead return SSL_ERROR_SSL) and
    therefore give a hint as to what went wrong.
    
    Contains a partial fix for #10880
    
    Reviewed-by: Tomas Mraz <tmraz@fedoraproject.org>
    Reviewed-by: Dmitry Belyavskiy <beldmit@gmail.com>
    (Merged from https://github.com/openssl/openssl/pull/10882)
```

**Comment by er-1** [comment]
About `test_ssl`, the issue related with the following message was fixed in the python 3.8 and in the main branch: `ssl.SSLError: ('tlsv13 alert certificate required',)`

AT next follows python 3.7. It might be worth a try with a newer version.

**Comment by mscastanho** [comment]
I tried using 3.8 and master, but the patch `python-3.7-getlib64s2.patch` does not apply cleanly:
```
$ patch -p1 < python-3.7-getlib64s2.patch
[...]
patching file Lib/pydoc.py
Hunk #1 succeeded at 366 (offset 1 line).
Hunk #2 FAILED at 400.
[...]
patching file Lib/trace.py
Hunk #1 succeeded at 61 (offset 1 line).
Hunk #2 FAILED at 660.
[...]
```

This problem starts on Python commit:
```
commit ca133e53fafdec1aa77613fcb7558deed959383f (HEAD)
Author: Miss Islington (bot) <31488909+miss-islington@users.noreply.github.com>
Date:   Wed Feb 12 04:32:46 2020 -0800

    bpo-21016: pydoc and trace use sysconfig (GH-18476)
    
    
    bpo-21016, bpo-1294959: The pydoc and trace modules now use the
    sysconfig module to get the path to the Python standard library, to
    support uncommon installation path like /usr/lib64/python3.9/ on
    Fedora.
    
    Co-Authored-By: Jan Matějek <jmatejek@suse.com>
    (cherry picked from commit 4fac7ed43ebf1771a8fe86fdfe7b9991f3be78cd)
    
    Co-authored-by: Victor Stinner <vstinner@python.org>
```
This commit and our patch seem to be doing very similar things: getting Python stdlib dir from sysconfig.

This is also on the 3.7 branch, so this problem will arise eventually when we update the Python revision.

**Comment by mscastanho** [comment]
I fixed the patch and successfully built with Python 3.8. But the failing tests remain.

**Comment by er-1** [comment]
> I fixed the patch and successfully built with Python 3.8. But the failing tests remain.

I got the same result with Python 3.9.

**Comment by mscastanho** [comment]
I just confirmed my previous suspicion. Both `test_ssl` and `test_urllib2_localnet` failures are caused by OpenSSL commit `db943f43a60d1b5b1277e4b5317e8f288e7a0a3` (Detect EOF while reading in libssl).

**Comment by mscastanho** [comment]
Looks like an actual fix will require some changes to Python's source code to handle the new error introduced by the breaking commit, so I opened an issue on Python's bug tracker: [Issue 39787](https://bugs.python.org/issue39787)

**Comment by mscastanho** [comment]
This issue has now been reported by other people on [Python bug tracker](https://bugs.python.org/issue40018).

**Comment by mscastanho** [comment]
The broken OpenSSL commit has been partially reverted upstream:  openssl/openssl#11400

However, it only applies to branch `OpenSSL_1_1_1-stable`. Apparently they are keeping the new behavior for the newest version.

@er-1 Are we building with top-of-tree OpenSSL?

**Comment by er-1** [comment]
> @er-1 Are we building with top-of-tree OpenSSL?

@mscastanho AT next takes, in best case, the head of the branch `OpenSSL_1_1_1-stable`.

**Comment by mscastanho** [comment]
Other people reported that the revert fixed the problems for `v1.1.1` ([link](https://bugs.python.org/issue40018#msg365148)) 

Still, the new behaviour that caused the issue will be present on the next OpenSSL release ([3.0.0, scheduled for early Q4 2020](https://www.openssl.org/blog/blog/2019/11/07/3.0-update/)). 

Python devs are already taking care of it to make sure the issue is properly handled upstream: [issue 38820](https://bugs.python.org/issue38820).

So I'll close this issue to let Cherbot bump and test the newest revision.

**Pull request closed without merging**
