### PR TITLE
Update binutils on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 7d0aa7cbd4ce

### CODE REVIEW

**Comment by er-1** [comment]
The builds failed while compiling `pveclib`:
```
libtool: compile:  /home/tcbot/bot-slave/at_opt/at-next-16.0-0-alpha/bin/powerpc64le-linux-gnu-gcc -m64 -DPACKAGE_NAME=\"pveclib\" -DPACKAGE_TARNAME=\"pveclib\" -DPACKAGE_VERSION=\"1.0.4\" "-DPACKAGE_STRING=\"pveclib 1.0.4\"" "-DPACKAGE_BUGREPORT=\"munroesj52@gmail.com pc@us.ibm.com\"" -DPACKAGE_URL=\"https://github.com/open-power-sdk/pveclib\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"pveclib\" -DVERSION=\"1.0.4\" -DHAVE_ALTIVEC_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDIO_H=1 -DHAVE_FENV_H=1 -DHAVE_FLOAT_H=1 -DHAVE_MATH_H=1 -DPVECLIB_DISABLE_POWER7=1 -I. -I/home/tcbot/bot-worker/at/src/at16.0-0-alpha.debian-10_ppc64le_ppc64le/sources/pveclib/src -DNDEBUG -DNDEBUG -m64 -O3 -g -O -MT testsuite/libvecdummy_la-vec_f128_dummy.lo -MD -MP -MF testsuite/.deps/libvecdummy_la-vec_f128_dummy.Tpo -c /home/tcbot/bot-worker/at/src/at16.0-0-alpha.debian-10_ppc64le_ppc64le/sources/pveclib/src/testsuite/vec_f128_dummy.c  -fPIC -DPIC -o testsuite/.libs/libvecdummy_la-vec_f128_dummy.o
/tmp/cc4GBijz.s: Assembler messages:
/tmp/cc4GBijz.s:24523: Error: unrecognized opcode: `xsaddqp'
/tmp/cc4GBijz.s:24580: Error: unrecognized opcode: `xsdivqp'
/tmp/cc4GBijz.s:24637: Error: unrecognized opcode: `xsmulqp'
/tmp/cc4GBijz.s:24693: Error: unrecognized opcode: `xssubqp'
make[2]: *** [Makefile:1130: testsuite/libvecdummy_la-vec_f128_dummy.lo] Error 1
```

**Comment by ThinkOpenly** [comment]
> The builds failed while compiling `pveclib`:
> 
> ```
> libtool: compile:  /home/tcbot/bot-slave/at_opt/at-next-16.0-0-alpha/bin/powerpc64le-linux-gnu-gcc -m64 -DPACKAGE_NAME=\"pveclib\" -DPACKAGE_TARNAME=\"pveclib\" -DPACKAGE_VERSION=\"1.0.4\" "-DPACKAGE_STRING=\"pveclib 1.0.4\"" "-DPACKAGE_BUGREPORT=\"munroesj52@gmail.com pc@us.ibm.com\"" -DPACKAGE_URL=\"https://github.com/open-power-sdk/pveclib\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"pveclib\" -DVERSION=\"1.0.4\" -DHAVE_ALTIVEC_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDIO_H=1 -DHAVE_FENV_H=1 -DHAVE_FLOAT_H=1 -DHAVE_MATH_H=1 -DPVECLIB_DISABLE_POWER7=1 -I. -I/home/tcbot/bot-worker/at/src/at16.0-0-alpha.debian-10_ppc64le_ppc64le/sources/pveclib/src -DNDEBUG -DNDEBUG -m64 -O3 -g -O -MT testsuite/libvecdummy_la-vec_f128_dummy.lo -MD -MP -MF testsuite/.deps/libvecdummy_la-vec_f128_dummy.Tpo -c /home/tcbot/bot-worker/at/src/at16.0-0-alpha.debian-10_ppc64le_ppc64le/sources/pveclib/src/testsuite/vec_f128_dummy.c  -fPIC -DPIC -o testsuite/.libs/libvecdummy_la-vec_f128_dummy.o
> /tmp/cc4GBijz.s: Assembler messages:
> /tmp/cc4GBijz.s:24523: Error: unrecognized opcode: `xsaddqp'
> /tmp/cc4GBijz.s:24580: Error: unrecognized opcode: `xsdivqp'
> /tmp/cc4GBijz.s:24637: Error: unrecognized opcode: `xsmulqp'
> /tmp/cc4GBijz.s:24693: Error: unrecognized opcode: `xssubqp'
> make[2]: *** [Makefile:1130: testsuite/libvecdummy_la-vec_f128_dummy.lo] Error 1
> ```

Those instructions are new in Power ISA 3.0 (POWER9), yet the compilation is done without any `-mcpu` options to enable POWER9 instructions, nor any similar inline compiler directives. I think this manifests now because of a change to GCC (I think) to no longer pass `-many` to `as`. This is effectively a bug in pveclib, which should be explicitly requesting the Power ISA 3.0 instruction set when it needs it, via `-mcpu=power9`, `.machine power9`, or similar.

**Comment by ThinkOpenly** [comment]
> > The builds failed while compiling `pveclib`:

> This is effectively a bug in pveclib, which should be explicitly requesting the Power ISA 3.0 instruction set when it needs it, via `-mcpu=power9`, `.machine power9`, or similar.

I opened https://github.com/open-power-sdk/pveclib/issues/150

**Comment by munroesj52** [comment]
Perhaos from this:

// TBD will sub-in pveclib softfloat for P8 when available

__float128
test_scalar_add128 (__float128 vra, __float128 vrb)
{
#ifndef __clang__
  if (__builtin_cpu_supports("ieee128"))
    {
      __float128 result;
      __asm__(
	      "xsaddqp %0,%1,%2"
	      : "=v" (result)
	      : "v" (vra), "v" (vrb)
	      : );
      return result;
    }
  else
    // Generate call to __addkf3
    return (vra + vrb);
#else
  return vra;
#endif
}

which should be guarded by:

#ifndef PVECLIB_DISABLE_F128ARITH
#ifdef __FLOAT128__

These are compile only tests

Should be able to work around by by wrapping these in

#ifdef _ARCH_PWR9
#endif

**Comment by munroesj52** [comment]
BTW what is AT16? do you have a AT15 ready?

Also what version of PVECLIB?

**Comment by er-1** [comment]
> BTW what is AT16?

It's the next version, it'll be released in 2022, so it's mostly in progress?

> do you have a AT15 ready?

Not yet, it's planned for the end of August.

> Also what version of PVECLIB?

1.0.4, commit https://github.com/open-power-sdk/pveclib/commit/64246b4af5390051416747129c4def985efb966c

**Comment by ThinkOpenly** [comment]
Upstream pveclib fix has been merged. Do we close this and expect a new pull request from @Cherbot to trigger a new build?

**Comment by mscastanho** [comment]
@ThinkOpenly Yes, we should close this one.

But note that it would require to have the pveclib changes merged before the binutils update, which may take 2 weeks using the regular Cherbot update schedule.

To save some time, we can force a pveclib update beforehand (#2285), but we need a second fix upstream to get that merged (open-power-sdk/pveclib#152).

**Comment by ThinkOpenly** [comment]
> @ThinkOpenly Yes, we should close this one.
> 
> But note that it would require to have the pveclib changes merged before the binutils update, which may take 2 weeks using the regular Cherbot update schedule.
> 
> To save some time, we can force a pveclib update beforehand (#2285), but we need a second fix upstream to get that merged ([open-power-sdk/pveclib#152](https://github.com/open-power-sdk/pveclib/pull/152)).

([open-power-sdk/pveclib#152](https://github.com/open-power-sdk/pveclib/pull/152)) has been merged. To force the update, what needs to be done? Close #2285 first? Then wait for the pveclib update before closing this?

**Comment by mscastanho** [comment]
@ThinkOpenly We need to close the existing PR (#2285) and then manually trigger Cherbot only for pveclib. I have just done that, which resulted on #2286. Once all tests pass, that PR will be automatically merged.

We also need to close this PR, so Cherbot can create a new one for binutils tomorrow, rebased against the latest master, which will include the pveclib fix.

So this can be closed now.

**Pull request closed without merging**
