### PR TITLE
Update binutils on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 3580810c51bc

### CODE REVIEW

**Comment by er-1** [comment]
It failed while building `binutils`:
```
In file included from /home/tcbot/bot-worker/at/src/at14.0-0-alpha.debian-10_ppc64le_ppc64le/sources/binutils/gdbserver/server.h:22,
                 from /home/tcbot/bot-worker/at/src/at14.0-0-alpha.debian-10_ppc64le_ppc64le/sources/binutils/gdbserver/proc-service.cc:21:
/home/tcbot/bot-worker/at/src/at14.0-0-alpha.debian-10_ppc64le_ppc64le/sources/binutils/gdbserver/../gdbsupport/common-defs.h:25:10: fatal error: gnulib/config.h: No such file or directory
 #include <gnulib/config.h>
          ^~~~~~~~~~~~~~~~~
```

**Comment by mscastanho** [comment]
This is most likely related to commit `1a627e7e6c61e`:
```
[binutils-gdb]$ git log --no-walk 1a627e7e6c61e
commit 1a627e7e6c61e97951932e3a9c5fb706efe3ef3e
Author: Tom Tromey <tom@tromey.com>
Date:   Fri Feb 14 14:34:20 2020 -0700

    Change gdbserver to use existing gnulib and libiberty
    
    This changes gdbserver so that it no longer builds its own gnulib and
    libiberty.  Instead, it now relies on the ones that were already built
    at the top level.
    
    gdbsupport is still built specially for gdbserver.  This is more
    complicated and will be tackled in a subsequent patch.
    
    ChangeLog
    2020-02-14  Tom Tromey  <tom@tromey.com>
    
            * Makefile.in: Rebuild.
            * Makefile.def: Make gdbserver require gnulib and libiberty.
    
    gdbserver/ChangeLog
    2020-02-14  Tom Tromey  <tom@tromey.com>
    
            * acinclude.m4: Don't include acx_configure_dir.m4.
            * Makefile.in (LIBIBERTY_BUILDDIR, GNULIB_BUILDDIR): Update.
            (SUBDIRS, CLEANDIRS, REQUIRED_SUBDIRS): Remove.
            (all, install-only, uninstall, clean-info, clean)
            (maintainer-clean): Don't recurse.
            (subdir_do, all-lib): Remove.
            ($(LIBGNU) $(LIBIBERTY) $(GNULIB_H)): Remove rule.
            (GNULIB_H): Remove.
            (generated_files): Update.
            ($(GNULIB_BUILDDIR)/Makefile): Remove rule.
            * configure: Rebuild.
            * configure.ac: Don't configure gnulib or libiberty.
            (GNULIB): Update.
    
    gdbsupport/ChangeLog
```

**Comment by mscastanho** [comment]
@er-1 This problem was indeed caused by the commit above, but @pedromfcarvalho correctly noted that it has already been fixed upstream by `b6f9caee52be`:

```
commit b6f9caee52be22ec3ff46f2773aef473625b8033
Author: Tom Tromey <tom@tromey.com>
Date:   Mon Feb 17 10:00:26 2020 -0700

    Fix gdbserver-without-gdb build
    
    An earlier patch changed gdbserver to use the already-built top-level
    gnulib and gdbsupport.  However, if one did a build that did not
    include gdb, then gdbserver would fail to build.
    
    The problem is that configure.ac only adds gnulib and gdbsupport to
    the build when gdb is being built.  This patch fixes the problem by
    arranging for this to happen when gdbserver is built.
    
    ChangeLog
    2020-02-17  Tom Tromey  <tom@tromey.com>
    
            * configure: Rebuild.
            * configure.ac (configdirs): Add gnulib and gdbsupport when building
            gdbserver.
```

So we can close this and just merge the next automated bump.

**Comment by er-1** [comment]
> So we can close this and just merge the next automated bump.
Closing this.

**Pull request closed without merging**
