### PR TITLE
Update valgrind on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 476b52d62dd9

### CODE REVIEW

**Comment by gftg85** [comment]
The build on Ubuntu 16.04 did not finish (could not generate the .deb files, hence fvtr did not run).

**Comment by gftg85** [comment]
Since the fvtr on Ubuntu 16.04 did not run.  Should we close this pull request?  Or should we merge it because it succeeded on Ubuntu 14.04 and SLES 12 (apart from the known python failure)?

**Comment by tuliom** [comment]
A lazy way of checking this is to reject this PR, wait for the next patch from cherbot and see if it passes all tests.

**Comment by gftg85** [comment]
I like this approach (i.e.: delete the pull request and wait for the next automatic update).

**Pull request closed without merging**
