### PR TITLE
Update valgrind on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 2052837a3e0b

### CODE REVIEW

**Comment by er-1** [comment]
Same issue as in #1256 
```
it_main.c: In function ‘vgItrace_post_clo_init’:
it_main.c:353:22: error: ‘VexControl’ has no member named ‘guest_chase_thresh’
  353 |  VG_(clo_vex_control).guest_chase_thresh = 0;
      |                      ^
```

@willschm Do you know if your fix is available upstream?

**Comment by willschm** [comment]
> Same issue as in #1256
> 
> ```
> it_main.c: In function ‘vgItrace_post_clo_init’:
> it_main.c:353:22: error: ‘VexControl’ has no member named ‘guest_chase_thresh’
>   353 |  VG_(clo_vex_control).guest_chase_thresh = 0;
>       |                      ^
> ```
> 
> @willschm Do you know if your fix is available upstream?
Should be.   (double-checking).
The fix is in the current itrace tree (github.ibm.com/valgrind-itrace).  Is that different than your upstream?

**Comment by er-1** [comment]
@willschm my bad, I mixed up `valgrind` and `valgrind-itrace`.

**Comment by willschm** [comment]
> @willschm my bad, I mixed up `valgrind` and `valgrind-itrace`.

:-)

The error referenced:
it_main.c:353:22: error: ‘VexControl’ has no member named ‘guest_chase_thresh’
  353 |  VG_(clo_vex_control).guest_chase_thresh = 0;

suggests that the fix for itrace (it_main.c) has not been applied to the source tree you are working with.
Upstream Valgrind replaced the integral  guest_chase_thresh variable with a boolean guest_chase variable.   The itrace fix made the same change, so 'head' for both should play nicely.

**Pull request closed without merging**
