### PR TITLE
Move AT 15.0 to python branch 3.9

### PR DESCRIPTION
**Pull request by er-1**
AT 15.0 will track the 3.9 branch, whereas AT next will track the 3.10 branch.

Signed-off-by: Erwan Prioul <erwan@linux.ibm.com>

### CODE REVIEW

**Comment by er-1** [comment]
AT next failed while building pveclib.
AT next is using the same pveclib as AT 15.0. Since 2b86315ea5051e5486730e342e, AT next has failed to build. PR #2216 should fix it.

**Comment by mscastanho** [comment]
I was surprised that even though the `3.10` branch does not contain commit `91db097358bc` (from `next/packages/python/sources`) the build did not fail.

**Comment by er-1** [comment]
> I was surprised that even though the `3.10` branch does not contain commit `91db097358bc` (from `next/packages/python/sources`) the build did not fail.

That's a trick.
When building, it takes only the revision in account.
`update_revision.sh` will bump the revision (and the version) based on the branch.

**Comment by mscastanho** [comment]
Oh, nice. Good to know. Thanks for the explanation.

**Review by mscastanho — APPROVED** [review]
LGTM.

**Pull request merged**
