### PR TITLE
Update GCC on AT next

### PR DESCRIPTION
**Pull request by tuliom**
The first patches prepare other packages to build with the latest revision from GCC 8.

The last patch is the final update.

I think PR #375 should be discarded now.

### CODE REVIEW

**Comment by tuliom** [comment]
Notice the first patch is being reviewed as PR #381.

**Comment by tuliom** [comment]
It seems GCC didn't like my changes to libpfm on AT 6.0.  I'm going to recreate this patch and remove that symlink.

**Comment by tuliom** [comment]
I updated this patchset to version 2.
I hope that PR #381 can be reviewed here now.

**Comment by rzinsly** [comment]
Not sure why but seems our CI system tested commit 2eae851 instead of 1432159.

**Comment by tuliom** [comment]
2eae851776cc32c086cce2876d07de03afab98e1 is indeed the right commit ID to be tested.  Github doesn't exhibit the right commit log.

**Comment by tuliom** [comment]
I've disabled Python's test_random_fork based on aed7470235e2b49be1ceeff621996ad716e5fc73.
This should solve the Python failures in the previous version.

**Comment by tuliom** [comment]
Merged.

**Pull request closed without merging**
