### PR TITLE
Update glibc on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision bc2eb9321ec0

### CODE REVIEW

**Comment by er-1** [comment]
It failed while building `glibc`:
```
/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/bin/gcc -m64 ../sysdeps/unix/sysv/linux/gai_sigqueue.c -c -std=gnu11 -fgnu89-inline  -g -O3 -mlong-double-128 -fcommon -Wno-error=stringop-overflow= -mcpu=power8 -Wall -Wwrite-strings -Wundef -Werror -fmerge-all-constants -frounding-math -fno-stack-protector -Wstrict-prototypes -Wold-style-definition -fmath-errno -mlong-double-128  -fpic   -ftls-model=initial-exec    -isystem /home/tcbot/bot-worker/at/src/at14.0-0-alpha.debian-10_ppc64le_ppc64le/builds/glibc_2-64/systemtap  -I../include -I/home/tcbot/bot-worker/at/src/at14.0-0-alpha.debian-10_ppc64le_ppc64le/builds/glibc_2-64/resolv  -I/home/tcbot/bot-worker/at/src/at14.0-0-alpha.debian-10_ppc64le_ppc64le/builds/glibc_2-64  -I../sysdeps/unix/sysv/linux/powerpc/powerpc64/le/fpu  -I../sysdeps/unix/sysv/linux/powerpc/powerpc64/fpu  -I../sysdeps/unix/sysv/linux/powerpc/powerpc64/le  -I../sysdeps/unix/sysv/linux/powerpc/powerpc64  -I../sysdeps/unix/sysv/linux/wordsize-64  -I../sysdeps/unix/sysv/linux/powerpc  -I../sysdeps/powerpc/nptl  -I../sysdeps/unix/sysv/linux/include -I../sysdeps/unix/sysv/linux  -I../sysdeps/nptl  -I../sysdeps/pthread  -I../sysdeps/gnu  -I../sysdeps/unix/inet  -I../sysdeps/unix/sysv  -I../sysdeps/unix/powerpc  -I../sysdeps/unix  -I../sysdeps/posix  -I../sysdeps/powerpc/powerpc64/le/power8/fpu/multiarch  -I../sysdeps/powerpc/powerpc64/le/power7/fpu/multiarch  -I../sysdeps/powerpc/powerpc64/le/fpu/multiarch  -I../sysdeps/powerpc/powerpc64/le/power8/fpu  -I../sysdeps/powerpc/powerpc64/le/power7/fpu  -I../sysdeps/powerpc/powerpc64/le/fpu  -I../sysdeps/powerpc/powerpc64/fpu  -I../sysdeps/powerpc/powerpc64/le/power8/multiarch  -I../sysdeps/powerpc/powerpc64/le/power7/multiarch  -I../sysdeps/powerpc/powerpc64/le/multiarch  -I../sysdeps/powerpc/powerpc64/multiarch  -I../sysdeps/powerpc/powerpc64/le/power8  -I../sysdeps/powerpc/powerpc64/power8  -I../sysdeps/powerpc/powerpc64/le/power7  -I../sysdeps/powerpc/powerpc64/power7  -I../sysdeps/powerpc/powerpc64/power6  -I../sysdeps/powerpc/powerpc64/power4  -I../sysdeps/powerpc/power4  -I../sysdeps/powerpc/powerpc64/le  -I../sysdeps/powerpc/powerpc64  -I../sysdeps/wordsize-64  -I../sysdeps/powerpc/fpu  -I../sysdeps/powerpc  -I../sysdeps/ieee754/ldbl-128ibm/include -I../sysdeps/ieee754/ldbl-128ibm  -I../sysdeps/ieee754/ldbl-opt  -I../sysdeps/ieee754/dbl-64  -I../sysdeps/ieee754/flt-32  -I../sysdeps/ieee754/float128  -I../sysdeps/ieee754  -I../sysdeps/generic  -I.. -I../libio -I. -nostdinc -isystem /home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/gcc/powerpc64le-linux-gnu/10.0.1/include -isystem /home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib/gcc/powerpc64le-linux-gnu/10.0.1/include-fixed -isystem /home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/include  -D_LIBC_REENTRANT -include /home/tcbot/bot-worker/at/src/at14.0-0-alpha.debian-10_ppc64le_ppc64le/builds/glibc_2-64/libc-modules.h -DMODULE_NAME=libc -include ../include/libc-symbols.h  -DPIC -DSHARED     -DTOP_NAMESPACE=glibc -o /home/tcbot/bot-worker/at/src/at14.0-0-alpha.debian-10_ppc64le_ppc64le/builds/glibc_2-64/resolv/gai_sigqueue.os -MD -MP -MF /home/tcbot/bot-worker/at/src/at14.0-0-alpha.debian-10_ppc64le_ppc64le/builds/glibc_2-64/resolv/gai_sigqueue.os.dt -MT /home/tcbot/bot-worker/at/src/at14.0-0-alpha.debian-10_ppc64le_ppc64le/builds/glibc_2-64/resolv/gai_sigqueue.os
In file included from resolv_conf.c:27:
resolv_conf.c: In function ‘__resolv_conf_get_current’:
../include/file_change_detection.h:58:7: error: ‘initial.ctime.tv_nsec’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   53 |     return left->size == right->size
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |       && left->ino == right->ino
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |       && left->mtime.tv_sec == right->mtime.tv_sec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |       && left->mtime.tv_nsec == right->mtime.tv_nsec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   57 |       && left->ctime.tv_sec == right->ctime.tv_sec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   58 |       && left->ctime.tv_nsec == right->ctime.tv_nsec;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
resolv_conf.c:123:32: note: ‘initial.ctime.tv_nsec’ was declared here
  123 |   struct file_change_detection initial;
      |                                ^~~~~~~
In file included from resolv_conf.c:27:
../include/file_change_detection.h:57:7: error: ‘initial.ctime.tv_sec’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   53 |     return left->size == right->size
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |       && left->ino == right->ino
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |       && left->mtime.tv_sec == right->mtime.tv_sec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |       && left->mtime.tv_nsec == right->mtime.tv_nsec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   57 |       && left->ctime.tv_sec == right->ctime.tv_sec
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
resolv_conf.c:123:32: note: ‘initial.ctime.tv_sec’ was declared here
  123 |   struct file_change_detection initial;
      |                                ^~~~~~~
In file included from resolv_conf.c:27:
../include/file_change_detection.h:56:7: error: ‘initial.mtime.tv_nsec’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   53 |     return left->size == right->size
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |       && left->ino == right->ino
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |       && left->mtime.tv_sec == right->mtime.tv_sec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |       && left->mtime.tv_nsec == right->mtime.tv_nsec
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
resolv_conf.c:123:32: note: ‘initial.mtime.tv_nsec’ was declared here
  123 |   struct file_change_detection initial;
      |                                ^~~~~~~
In file included from resolv_conf.c:27:
../include/file_change_detection.h:55:7: error: ‘initial.mtime.tv_sec’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   53 |     return left->size == right->size
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |       && left->ino == right->ino
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |       && left->mtime.tv_sec == right->mtime.tv_sec
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
resolv_conf.c:123:32: note: ‘initial.mtime.tv_sec’ was declared here
  123 |   struct file_change_detection initial;
      |                                ^~~~~~~
In file included from resolv_conf.c:27:
../include/file_change_detection.h:54:7: error: ‘initial.ino’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   53 |     return left->size == right->size
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |       && left->ino == right->ino
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
resolv_conf.c:123:32: note: ‘initial.ino’ was declared here
  123 |   struct file_change_detection initial;
      |                                ^~~~~~~
resolv_conf.c: In function ‘__resolv_conf_attach’:
resolv_conf.c:476:17: note: the layout of aggregates containing vectors with 8-byte alignment has changed in GCC 5
  476 |   resp->retrans = conf->retrans;
      |   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [../o-iterator.mk:9: /home/tcbot/bot-worker/at/src/at14.0-0-alpha.debian-10_ppc64le_ppc64le/builds/glibc_2-64/resolv/resolv_conf.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from resolv_conf.c:27:
resolv_conf.c: In function ‘__resolv_conf_get_current’:
../include/file_change_detection.h:58:7: error: ‘initial.ctime.tv_nsec’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   53 |     return left->size == right->size
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |       && left->ino == right->ino
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |       && left->mtime.tv_sec == right->mtime.tv_sec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |       && left->mtime.tv_nsec == right->mtime.tv_nsec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   57 |       && left->ctime.tv_sec == right->ctime.tv_sec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   58 |       && left->ctime.tv_nsec == right->ctime.tv_nsec;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
resolv_conf.c:123:32: note: ‘initial.ctime.tv_nsec’ was declared here
  123 |   struct file_change_detection initial;
      |                                ^~~~~~~
In file included from resolv_conf.c:27:
../include/file_change_detection.h:57:7: error: ‘initial.ctime.tv_sec’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   53 |     return left->size == right->size
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |       && left->ino == right->ino
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |       && left->mtime.tv_sec == right->mtime.tv_sec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |       && left->mtime.tv_nsec == right->mtime.tv_nsec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   57 |       && left->ctime.tv_sec == right->ctime.tv_sec
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
resolv_conf.c:123:32: note: ‘initial.ctime.tv_sec’ was declared here
  123 |   struct file_change_detection initial;
      |                                ^~~~~~~
In file included from resolv_conf.c:27:
../include/file_change_detection.h:56:7: error: ‘initial.mtime.tv_nsec’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   53 |     return left->size == right->size
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |       && left->ino == right->ino
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |       && left->mtime.tv_sec == right->mtime.tv_sec
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |       && left->mtime.tv_nsec == right->mtime.tv_nsec
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
resolv_conf.c:123:32: note: ‘initial.mtime.tv_nsec’ was declared here
  123 |   struct file_change_detection initial;
      |                                ^~~~~~~
In file included from resolv_conf.c:27:
../include/file_change_detection.h:55:7: error: ‘initial.mtime.tv_sec’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   53 |     return left->size == right->size
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |       && left->ino == right->ino
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |       && left->mtime.tv_sec == right->mtime.tv_sec
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
resolv_conf.c:123:32: note: ‘initial.mtime.tv_sec’ was declared here
  123 |   struct file_change_detection initial;
      |                                ^~~~~~~
In file included from resolv_conf.c:27:
../include/file_change_detection.h:54:7: error: ‘initial.ino’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   53 |     return left->size == right->size
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |       && left->ino == right->ino
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
resolv_conf.c:123:32: note: ‘initial.ino’ was declared here
  123 |   struct file_change_detection initial;
      |                                ^~~~~~~
resolv_conf.c: In function ‘__resolv_conf_attach’:
resolv_conf.c:476:17: note: the layout of aggregates containing vectors with 8-byte alignment has changed in GCC 5
  476 |   resp->retrans = conf->retrans;
      |   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by tuliom** [comment]
This has been reported on libc-alpha too.
There is patch pending review: https://www.sourceware.org/ml/libc-alpha/2020-02/msg00744.html

**Comment by er-1** [comment]
Closing. We'll see Saturday if the patch is included or not.

**Comment by mscastanho** [comment]
The patch has just been pushed: https://www.sourceware.org/ml/libc-alpha/2020-02/msg00782.html

**Pull request closed without merging**
