### PR TITLE
Update gcc on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision eb9883c1312c

### CODE REVIEW

**Comment by er-1** [comment]
It keeps failing on SLES15 while running `perf` tests.
The tests time out:
```
command timed out: 10800 seconds without output running [b'nice', b'-n', b'19', b'make', b'test', b'DESTDIR=/home/tcbot/bot-slave/at_opt', b'AT_CONFIGSET=next'], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=10885.816003
```
Not much in the logs:
```
perf: power9:  Start logging...
```

**Comment by er-1** [comment]
The command that times out : `perf probe -v -x /path/to/AT/at-next-15.0-0-alpha/bin/ld test_perf_debug=main argc`

**Comment by ThinkOpenly** [comment]
> ```
> $ perf probe -v -x /path/to/AT/at-next-15.0-0-alpha/bin/ld test_perf_debug=main argc
> ```

`strace` doesn't seem to show anything interesting, which is somewhat surprising. The last thing printed is the call to display the last line of verbose output:
```
$ strace -f perf probe -v -x /path/to/AT/at-next-15.0-0-alpha/bin/ld test_perf_debug=main argc
openat(AT_FDCWD, "/path/to/AT/at-next-15.0-0-alpha/bin/ld", O_RDONLY) = 3
fcntl(3, F_GETFL)                       = 0x10000 (flags O_RDONLY|O_LARGEFILE)
fstat(3, {st_mode=S_IFREG|0755, st_size=3761448, ...}) = 0
mmap(NULL, 3761448, PROT_READ|PROT_WRITE, MAP_PRIVATE, 3, 0) = 0x7fff8f5e0000
close(3)                                = 0
write(2, "Open Debuginfo file: /path/to"..., 73Open Debuginfo file: /path/to/AT/at-next-15.0-0-alpha/bin/ld
) = 73
write(2, "Try to find probe point from deb"..., 40Try to find probe point from debuginfo.
) = 40
```

Looking at the task's stack shows it somewhere in kernel space (not surprising), but it's not clear (to me) where it is:
```
$ pstree -lp | grep perf
           |-screen(4341)-+-bash(4343)---strace(64490)---perf(64493)
$ /usr/bin/sudo cat /proc/64493/stack
[<0>] 0xc000000257043b20
$ /usr/bin/sudo grep --after-context=1 ' _end' /proc/kallsyms 
[sudo] password for pc: 
c000000002200000 B _end
c008000001880008 t char2uni     [nls_utf8]
```

**Comment by ThinkOpenly** [comment]
```
$ gdb /usr/bin/perf # probe -v -x /path/to/AT/at-next-15.0-0-alpha/bin/ld test_perf_debug=main argc
GNU gdb (GDB; SUSE Linux Enterprise 15) 8.3.1
Reading symbols from /usr/bin/perf...
(No debugging symbols found in /usr/bin/perf)
Missing separate debuginfos, use: zypper install perf-debuginfo-5.3.18-23.24.ppc64le
(gdb) r probe -v -x /path/to/AT/at-next-15.0-0-alpha/bin/ld test_perf_debug=main argc
Starting program: /usr/bin/perf probe -v -x /path/to/AT/at-next-15.0-0-alpha/bin/ld test_perf_debug=main argc
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
probe-definition(0): test_perf_debug=main argc 
symbol:main file:(null) line:0 offset:0 return:0 lazy:(null)
parsing arg: argc into argc
1 arguments
Open Debuginfo file: /path/to/AT/at-next-15.0-0-alpha/bin/ld
Try to find probe point from debuginfo.
^C
Program received signal SIGINT, Interrupt.
0x00007ffff7ced0a8 in ?? () from /usr/lib64/libdw.so.1
(gdb) bt
#0  0x00007ffff7ced0a8 in ?? () from /usr/lib64/libdw.so.1
#1  0x00007ffff7ced82c in ?? () from /usr/lib64/libdw.so.1
#2  0x00007ffff7ced88c in dwarf_offdie () from /usr/lib64/libdw.so.1
#3  0x00000001005060c4 in ?? ()
#4  0x0000000100506774 in debuginfo.find_trace_events ()
#5  0x00000001004fc574 in convert_perf_probe_events ()
#6  0x0000000100351800 in ?? ()
#7  0x000000010035210c in cmd_probe ()
#8  0x00000001003a67cc in ?? ()
#9  0x00000001003a6ec0 in ?? ()
#10 0x00000001002d0b40 in main ()
(gdb) 
```
...just data. I can't draw any conclusions from that, yet.

**Comment by ThinkOpenly** [comment]
Kernel ftrace after breaking in `main`, enabling the trace, then continuing:
```
  switch_mm_irqs_off() {
  finish_task_switch() {
  cgroup_leave_frozen() {
  recalc_sigpending_tsk();
  dequeue_signal() {
  single_step_exception() {
  do_notify_resume() {
  switch_mm_irqs_off();
  sys_access() {
  sys_newstat() {
  sys_rt_sigprocmask() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_write() {
  sys_write() {
  sys_write() {
  sys_write() {
  sys_write() {
  sys_newuname() {
  sys_openat() {
  sys_newfstat() {
  sys_read() {
  sys_geteuid() {
  sys_close() {
  do_notify_resume() {
  sys_access() {
  sys_openat() {
  sys_fcntl() {
  sys_newfstat() {
  sys_mmap() {
  sys_munmap() {
  sys_close() {
  do_notify_resume() {
  sys_access() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_newlstat() {
  sys_openat() {
  sys_dup() {
  sys_fcntl() {
  sys_newfstat() {
  sys_read() {
  sys_close() {
  sys_close() {
  do_notify_resume() {
  sys_openat() {
  do_notify_resume() {
  sys_openat() {
  do_notify_resume() {
  sys_openat() {
  do_notify_resume() {
  sys_openat() {
  sys_fcntl() {
  sys_newfstat() {
  sys_mmap() {
  sys_close() {
  sys_write() {
  sys_write() {
  timer_interrupt() {
  timer_interrupt() {
  timer_interrupt() {
  timer_interrupt() {
...
```
...which matches the `strace` output.  _hmm_

**Comment by ThinkOpenly** [comment]
Installed `libdw1-debuginfo` and `perf-debuginfo`.
It's in an endless loop in `debuginfo__find_probe_location`. Still digging...

**Comment by ThinkOpenly** [comment]
It's getting stuck in this loop:
```
	while (!dwarf_nextcu(dbg->dbg, off, &noff, &cuhl, NULL, NULL, NULL)) {
		/* Get the DIE(Debugging Information Entry) of this CU */
		diep = dwarf_offdie(dbg->dbg, off + cuhl, &pf->cu_die);
		if (!diep)
			continue;
...
		off = noff;
	}
```
What I observe there is that if the `continue` statement is executed, the `off` variable will never change (to `noff`), presumably these are "offset" and "next offset", which seems like the only way out of the loop.  Still digging...

**Comment by ThinkOpenly** [comment]
Suspicious changes between 2c356f221bba..eb9883c1312c:
```
commit b485fa167ef35c8facbd7c21cb86fd1abc77efcf
Author: Jakub Jelinek <jakub@redhat.com>
Date:   Fri Jan 22 22:37:36 2021 +0100

    dwarf2out: Always emit required 0 entries for DWARF 5 in *.debug_line [PR98796]
```
```
commit 27c792895bd809115c1f70672835b7fdff74d318
Author: Jakub Jelinek <jakub@redhat.com>
Date:   Wed Jan 20 18:51:04 2021 +0100

    debug: Fix up DWARF 5 -g -flto -ffat-lto-objects [PR98765]
```
```
commit 3804e937b0e252a7e42632fe6d9f898f1851a49c
Author: Mark Wielaard <mark@klomp.org>
Date:   Tue Sep 29 15:52:44 2020 +0200

    Default to DWARF5
```

**Comment by ThinkOpenly** [comment]
> It's getting stuck in this loop:
> 
> ```
> 	while (!dwarf_nextcu(dbg->dbg, off, &noff, &cuhl, NULL, NULL, NULL)) {
> 		/* Get the DIE(Debugging Information Entry) of this CU */
> 		diep = dwarf_offdie(dbg->dbg, off + cuhl, &pf->cu_die);
> 		if (!diep)
> 			continue;
> ...
> 		off = noff;
> 	}
> ```

I should note that the code above dates back to 2010/2013, so now leaning much more toward the GCC changes provoking the issue.  Even if GCC is doing something different, and it's the "right" thing, they apparently have a compatibility issue. I'll try a build with the suspicious changes above selectively reverted.

**Comment by ThinkOpenly** [comment]
Reverting just the one patch which is called "Default to DWARF5" allows the `perf probe` command to succeed:
```
perf probe -v -x /home/pc/opt/at-next-15.0-0-alpha/bin/ld ldmain=main
probe-definition(0): ldmain=main 
symbol:main file:(null) line:0 offset:0 return:0 lazy:(null)
0 arguments
Open Debuginfo file: /home/pc/opt/at-next-15.0-0-alpha/bin/ld
Try to find probe point from debuginfo.
Matched function: main [5e15f]
Probe point found: main+0
Found 1 probe_trace_events.
Opening /sys/kernel/debug/tracing//uprobe_events write=1
Writing event: p:probe_ld/ldmain /home/pc/opt/at-next-15.0-0-alpha/bin/ld:0x7848
Added new event:
  probe_ld:ldmain      (on main in /home/pc/opt/at-next-15.0-0-alpha/bin/ld)

You can now use it in all perf tools, such as:

        perf record -e probe_ld:ldmain -aR sleep 1
```
I'll bring this up on the GCC list.

**Comment by ThinkOpenly** [comment]
Posted to gcc-patches:
https://gcc.gnu.org/pipermail/gcc-patches/2021-January/564485.html

And opened a bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98875

**Comment by ThinkOpenly** [comment]
Posted to linux-perf-users:
https://www.spinics.net/lists/linux-perf-users/msg12579.html

**Comment by tuliom** [comment]
@ThinkOpenly Meanwhile, would it make sense to carry an out-of-tree patch in AT reverting the following commit?

```
commit 3804e937b0e252a7e42632fe6d9f898f1851a49c
Author: Mark Wielaard <mark@klomp.org>
Date:   Tue Sep 29 15:52:44 2020 +0200

    Default to DWARF5
```

I'm asking because it would allow us to continue updating GCC and give more time for this issue to be fixed upstream.

**Comment by ThinkOpenly** [comment]
> @ThinkOpenly Meanwhile, would it make sense to carry an out-of-tree patch in AT reverting the following commit?
> ```
> commit 3804e937b0e252a7e42632fe6d9f898f1851a49c
> Author: Mark Wielaard <mark@klomp.org>
> Date:   Tue Sep 29 15:52:44 2020 +0200
> 
>     Default to DWARF5
> ```
> I'm asking because it would allow us to continue updating GCC and give more time for this issue to be fixed upstream.

My sense is that this might not be "fixed upstream", and they'll expect applicaitons to "deal with it".

I'm not sure if we can expect SLES 15 to adopt a later version of `libdw` (or if that even helps). It's possible they'd adopt a "fix" to `perf`, but the one-line change just changes a hang into a failure, which still isn't good enough.

There is a command-line argument `-gdwarf-4`, which we could add to the AT build to produce DWARF4 instead of DWARF5. Would that be OK?

**Comment by tuliom** [comment]
> I'm not sure if we can expect SLES 15 to adopt a later version of `libdw` (or if that even helps).

@ThinkOpenly One can test this using this experimental package here:
https://software.opensuse.org/download/package?package=libdwarf&project=devel%3Atools

> There is a command-line argument `-gdwarf-4`, which we could add to the AT build to produce DWARF4 instead of DWARF5. Would that be OK?

This is a good workaround to let the test pass and buy us more time, but users would still not be able to run AT-compiled executables on SLES 15.

**Comment by ThinkOpenly** [comment]
> > I'm not sure if we can expect SLES 15 to adopt a later version of `libdw` (or if that even helps).
> 
> @ThinkOpenly One can test this using this experimental package here:
> https://software.opensuse.org/download/package?package=libdwarf&project=devel%3Atools

We could try this, sure.

> > There is a command-line argument `-gdwarf-4`, which we could add to the AT build to produce DWARF4 instead of DWARF5. Would that be OK?
> 
> This is a good workaround to let the test pass and buy us more time, but users would still not be able to run AT-compiled executables on SLES 15.

I don't follow this last statement. Why would DWARF4 format debugging information prevent running AT-compiled executable?

**Comment by tuliom** [comment]
> I don't follow this last statement. Why would DWARF4 format debugging information prevent running AT-compiled executable?

@ThinkOpenly , Ooops. I meant to say "users would still not be able to run AT-compiled executables **on perf** on SLES 15".

**Comment by ThinkOpenly** [comment]
> > > I'm not sure if we can expect SLES 15 to adopt a later version of `libdw` (or if that even helps).
> > 
> > 
> > @ThinkOpenly One can test this using this experimental package here:
> > https://software.opensuse.org/download/package?package=libdwarf&project=devel%3Atools
> 
> We could try this, sure.

Actually, that's `libdwarf` (which is also closely related to `libdwarf1`), but seems different/distinct from `libdw1`.

**Comment by ThinkOpenly** [comment]
> @ThinkOpenly Meanwhile, would it make sense to carry an out-of-tree patch in AT reverting the following commit?
> 
> ```
> commit 3804e937b0e252a7e42632fe6d9f898f1851a49c
> Author: Mark Wielaard <mark@klomp.org>
> Date:   Tue Sep 29 15:52:44 2020 +0200
> 
>     Default to DWARF5
> ```
> 
> I'm asking because it would allow us to continue updating GCC and give more time for this issue to be fixed upstream.

I'm starting to lean toward this being the long-term "fix", until `perf` and/or `libdw1` support is sufficient.  I'm not sure AT has a compelling interest in DWARF5, and the patch is fairly trivial:
```
diff --git a/gcc/common.opt b/gcc/common.opt
index a8a2b67a99d..7aff4ac6079 100644
--- a/gcc/common.opt
+++ b/gcc/common.opt
@@ -3182 +3182 @@ gdwarf-
-Common Driver Joined UInteger Var(dwarf_version) Init(5) Negative(gstabs)
+Common Driver Joined UInteger Var(dwarf_version) Init(4) Negative(gstabs)
```

**Comment by tuliom** [comment]
Fixed with #1954 .

**Pull request closed without merging**
