### PR TITLE
Update gcc on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 06a9f20f97e7

### CODE REVIEW

**Comment by mscastanho** [comment]
Cross builds failed on GCC stage 1:
```
In file included from /home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_x86_64_ppc64le/sources/gcc/libgcc/config/rs6000/_kf_to_sd.c:37:
/home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_x86_64_ppc64le/sources/gcc/libgcc/dfp-bit.c:32:10: fatal error: stdio.h: No such file or directory
   32 | #include <stdio.h>
      |          ^~~~~~~~~
compilation terminated.
make[3]: *** [/home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_x86_64_ppc64le/sources/gcc/libgcc/static-object.mk:17: _kf_to_sd.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_x86_64_ppc64le/sources/gcc/libgcc/config/rs6000/_kf_to_dd.c:37:
/home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_x86_64_ppc64le/sources/gcc/libgcc/dfp-bit.c:32:10: fatal error: stdio.h: No such file or directory
   32 | #include <stdio.h>
      |          ^~~~~~~~~
compilation terminated.
```

Likely related to:
```
commit 781183595acba67a37c66f59a0c1d9b5fee7e248
Author: Michael Meissner <meissner@linux.ibm.com>
Date:   Mon Feb 22 15:33:29 2021 -0500                                                                                                                                                                                                                       

Add conversions between _Float128 and Decimal.
```

Native builds failed on `ck_binaries` fvtr test:
```
Checking tgt file: /home/tcbot/bot-slave/at_opt/at-next-15.0-0-alpha/bin/powerpc64le-linux-gnu-gcc-11.0.0
Error:  File  /home/tcbot/bot-slave/at_opt/at-next-15.0-0-alpha/bin/powerpc64le-linux-gnu-gcc-11.0.0 is missing.
```

**Comment by er-1** [comment]
The `ck_binaries` failure might come from the mismatch between the upstream version (11.0.1) and the version stored in AT (11.0.0).

**Comment by mscastanho** [comment]
So maybe AT is actually building `powerpc64le-linux-gnu-gcc-11.0.1`, while the test is looking for `powerpc64le-linux-gnu-gcc-11.0.0`?

Do you think changing `ATSRC_PACKAGE_VER` on our gcc sources file to `11.0.1` is enough to fix that?

**Comment by mscastanho** [comment]
[There is a patch](https://gcc.gnu.org/pipermail/gcc-patches/2021-February/565917.html) for the cross build error being discussed on gcc-patches.

**Comment by er-1** [comment]
> Do you think changing `ATSRC_PACKAGE_VER` on our gcc sources file to `11.0.1` is enough to fix that?

I sent #1990 to confirm.

**Comment by mscastanho** [comment]
I documented the cross-compiler failure on #2017. We can close this now to allow Cherbot to create new PRs later.

**Pull request closed without merging**
