### PR TITLE
Provide -release package for SLES

### LINKED ISSUE #1372: Provide a -release package for SLES
openSUSE and SLES use an extra package called `-release` to provide metadata to libzypp.
This package provides information about a product, its repository, target distro, etc.
I'm still looking for a documentation or example for this package.

### PR DESCRIPTION
**Pull request by er-1**
Added a spec file to build a -release package for SLES only.
This package provides information about a product, its repository, target distro, etc.

Fix #1372

Signed-off-by: Erwan Prioul <erwan@linux.ibm.com>

### CODE REVIEW

**Comment by ThinkOpenly** [comment]
> tuliom requested a review from ThinkOpenly 7 days ago

I was hoping to see the results from:
> > Is it possible to do that, to run zypper product-info ... with the new package and validate the results?
> 
> I'll check that.

**Comment by er-1** [comment]
> Is it possible to do that, to run zypper product-info ... with the new package and validate the results?

Done. I updated the test `package-check` to validate the release package (using zypper in case the package is installed).

**Review by ThinkOpenly — APPROVED** [review]
Seems OK :crossed_fingers:

**Comment by er-1** [comment]
The build failure for AT 12.0 on SLES12 isn't related with this PR.

**Pull request merged**
