### PR TITLE
Update gcc on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision c9c05f7323f2

### CODE REVIEW

**Comment by tuliom** [comment]
AT next Debian10 ppc64le 487 failed with:
```
gdb/ada-lang.c:13593:50: error: ‘class std::basic_string_view<char>’ has no member named ‘to_string’
13593 |    = user_name.substr (1, user_name.size () - 2).to_string ();
      |                                                  ^~~~~~~~~
```

**Comment by mscastanho** [comment]
The funny thing is that this problem happened in GDB stage 1 build and that line was changed by commit:
```
commit e0802d59969339502203ad8e0d161b5f93beca73
Author: Tom Tromey <tromey@adacore.com>
Date:   Wed Apr 1 07:47:13 2020 -0600

    Avoid copying in lookup_name_info
```
Which has already been included in our builds for some time.

**Comment by tuliom** [comment]
The issue has been reported to GDB upstream here: https://sourceware.org/bugzilla/show_bug.cgi?id=26183

**Comment by peter-bergner** [comment]
The bug is due to a latent issue in gdb.  It was exposed now, because the trunk g++ now defaults to C++17.  A patch has been submitted upstream by Tom Tromey.

**Comment by mscastanho** [comment]
The patch pointed by @peter-bergner has just gone in:
```
commit 5ac588997c3c2d032d5d5145d9245eb37354c23b
Author: Tom Tromey <tromey@adacore.com>
Date:   Tue Jun 30 07:53:03 2020 -0600

    Do not define basic_string_view::to_string
```
I'll close this and we can bump gdb later to incorporate this fix.

**Pull request closed without merging**
