### PR TITLE
Update glibc on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision b5b7fb76e15c

### CODE REVIEW

**Comment by mscastanho** [comment]
GCC stage 4 is failing with:
```
make[3]: Leaving directory '/home/mscastanho/AT/next/tmp/build/at14.0-0-alpha.redhat-8_ppc64le_ppc64le/builds/gcc_4/gotools'
./fpu-target.h: In function 'set_fpu_except_flags.constprop':
./fpu-target.h:268:3: error: Argument must be a constant between 0 and 31.
  268 |   feraiseexcept (exc_set);
      |   ^
./fpu-target.h: In function 'ieee_procedure_entry':
./fpu-target.h:268:3: error: Argument must be a constant between 0 and 31.
  268 |   feraiseexcept (exc_set);
      |   ^
./fpu-target.h: In function 'ieee_procedure_exit':
./fpu-target.h:267:3: error: Argument must be a constant between 0 and 31.
  267 |   feclearexcept (exc_clr);
      |   ^
lto-wrapper: fatal error: /home/mscastanho/AT/next/tmp/build/at14.0-0-alpha.redhat-8_ppc64le_ppc64le/builds/gcc_4/./gcc/xgcc returned 1 exit status
compilation terminated.
/home/mscastanho/AT/next/opt/at-next-14.0-0-alpha/powerpc64le-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

**Comment by mscastanho** [comment]
These are the commits included with the latest bump:
```
[glibc]$ git log a92ac9f494b2..b5b7fb76e15c --oneline 
b5b7fb76e1 i386: Use comdat instead of .gnu.linkonce for i386 setup pic register (BZ #20543)
4068b54c70 ldbl-128ibm-compat: link tst-ldbl-efgcvt against loader too
77d5bddd8f ldbl-128ibm-compat: enforce ibm128 on compat tests
d967237443 ldbl-128ibm-compat: Provide nexttoward functions
f1a166b0d7 ldbl-128ibm-compat: Provide a significand implementation
39b47ada8d ldbl-128ibm-compat: Redirect complex math functions
8dbfea3a20 ldbl-128ibm-compat: Redirect long double functions to f128/ieee128 functions
6437fecca3 posix: Remove posix waitid
b3b6a40ab9 posix: Refactor tst-waitid (BZ #14666)
dfe9aa9156 support: Add support_process_state_wait
5c8aa3849a malloc/tst-mallocfork2: Kill lingering process for unexpected failures
758599bc9d elf: Apply attribute_relro to pointers in elf/dl-minimal.c
f1a0840c15 powerpc: Refactor fenvinline.h
d423e17031 nss_nis: Use NSS_DECLARE_MODULE_FUNCTIONS
783e641fba csu: Use ELF constructor instead of _init in libc.so
```

**Comment by mscastanho** [comment]
I'm afraid this problem may be related to commit
```
commit f1a0840c15d039631c13258544cdc04e4cbb9c69
Author: Rogerio Alves <rcardoso@linux.ibm.com>
Date:   Mon Feb 10 12:09:02 2020 -0300

    powerpc: Refactor fenvinline.h
    
    This patch refactor fenviline.h replaces some statements for
    builtins.
    
    Reviewed-by: Tulio Magno Quites Machado Filho <tuliom@linux.ibm.com>
```
which changes de definition of the macros `feraiseexcept` and `feclearexcept` on powerpc.

**Comment by mscastanho** [comment]
Fixed upstream:
```
$ git log --no-walk 1c252f0e7e5d
commit 1c252f0e7e5d78695f19450aa7c470bab445aa8e
Author: Matheus Castanho <msc@linux.ibm.com>
Date:   Tue Mar 3 15:20:38 2020 -0300

    powerpc: Fix feraiseexcept and feclearexcept macros
    
    A recent change to fenvinline.h modified the check if __e is a
    a power of 2 inside feraiseexcept and feclearexcept macros.  It
    introduced the use of the powerof2 macro but also removed the
    if statement checking whether __e != 0 before issuing an mtfsb*
    instruction.  This is problematic because powerof2 (0) evaluates
    to 1 and without the removed if __e is allowed to be 0 when
    __builtin_clz is called.  In that case the value 32 is passed
    to __MTFSB*, which is invalid.
    
    This commit uses __builtin_popcount instead of powerof2 to fix this
    issue and avoid the extra check for __e != 0.  This was the approach
    used by the initial versions of that previous patch.
    
    Reviewed-by: Tulio Magno Quites Machado Filho <tuliom@linux.ibm.com>
```

**Comment by er-1** [comment]
Closing to let Cherbot create a new PR taking head of glibc.

**Pull request closed without merging**
