### PR TITLE
Fix wording in packages descriptions

### PR DESCRIPTION
**Pull request by er-1**
Signed-off-by: Erwan Prioul <erwan@linux.ibm.com>

### CODE REVIEW

**Review by mscastanho — COMMENTED** [review]
Should these files be updated as well?
- `configs/13.0/deb/monolithic_cross/control`
- `configs/13.0/specs/metapkgs.spec`
- `configs/13.0/specs/monolithic_at-compat.spec`
- `configs/13.0/specs/monolithic_compat.spec`
- `configs/13.0/specs/monolithic_cross.spec`

**Comment by er-1** [comment]
> Should these files be updated as well?
> 
>     * `configs/13.0/deb/monolithic_cross/control`
> 
>     * `configs/13.0/specs/metapkgs.spec`
> 
>     * `configs/13.0/specs/monolithic_at-compat.spec`
> 
>     * `configs/13.0/specs/monolithic_compat.spec`
> 
>     * `configs/13.0/specs/monolithic_cross.spec`

Good point.
I updated them also.

**Review by mscastanho — APPROVED** [review]

**Comment by mscastanho** [comment]
This is one stop closer to closing #641

**Review by rzinsly — COMMENTED** [review]
The patches look good to me, I'm just not sure about the naming: "Advance Toolchain for Linux on IBM Power", is this the official name?
The documentation have this name without the IBM in many parts like in https://www.ibm.com/support/pages/advtool-usage and in the past I've seen the IBM at the beginning as "IBM Advance Toolchain for Linux on Power"

**Review by rzinsly — APPROVED** [review]
> I'm just not sure about the naming: "Advance Toolchain for Linux on IBM Power", is this the official name?

Seems it is, LGTM.

**Comment by er-1** [comment]
> The patches look good to me, I'm just not sure about the naming: "Advance Toolchain for Linux on IBM Power", is this the official name? The documentation have this name without the IBM in many parts like in https://www.ibm.com/support/pages/advtool-usage and in the past I've seen the IBM at the beginning as "IBM Advance Toolchain for Linux on Power"

I took "Advance Toolchain for Linux on IBM Power" from https://www.ibm.com/support/pages/advance-toolchain-linux-power, assuming (bad habits) it's the correct name. Actually, even in the page it's not that clear.

This PR is a follow up of this https://github.com/advancetoolchain/advance-toolchain/pull/2457#discussion_r736218186

**Pull request merged**
