### PR TITLE
Update gcc on AT next

### PR DESCRIPTION
**Pull request by er-1**
Bump to version 11.0.1
Bump to revision ~~06a9f20f97e7~~  f1d012911bd1

Close #2020 

Signed-off-by: Erwan Prioul <erwan@linux.ibm.com>

### CODE REVIEW

**Comment by mscastanho** [comment]
@er-1 Thanks for fixing the version string. Now we just need to wait for the fix for the cross compiler upstream so we can use that new revision. A [v2](https://gcc.gnu.org/pipermail/gcc-patches/2021-March/566023.html) is already under review

**Comment by er-1** [comment]
Failure are related with #2017

**Comment by mscastanho** [comment]
@er-1 Could you update the revision to `f1d012911bd103e9701ed378f32928a3cbcf028a`? It should contain the fix [1] and pass all tests.

https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=f1d012911bd103e9701ed378f32928a3cbcf028a

**Comment by er-1** [comment]
> @er-1 Could you update the revision to `f1d012911bd103e9701ed378f32928a3cbcf028a`? It should contain the fix [1] and pass all tests.

Done.

**Review by mscastanho — APPROVED** [review]

**Pull request merged**
