### PR TITLE
Update valgrind on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision fee5954ae0d6

### CODE REVIEW

**Comment by gftg85** [comment]
The logs for the failing build (AT Next RHEL7) contain messages similar to these:

```
so_KE.ISO-8859-1... done
so_SO.UTF-8...locale 'ar_BH.iso88596' already exists
cannot extend locale archive file
make[1]: *** [Makefile:422: install-archive-sid_ET/UTF-8] Error 1
make[1]: *** Waiting for unfinished jobs....
locale 'ar_BH.iso88596' already exists
cannot extend locale archive file
make[1]: *** [Makefile:422: install-archive-so_DJ/ISO-8859-1] Error 1
locale 'ar_BH.iso88596' already exists
cannot extend locale archive file
make[1]: *** [Makefile:422: install-archive-sc_IT/UTF-8] Error 1
locale 'ar_BH.iso88596' already exists
cannot extend locale archive file
make[1]: *** [Makefile:422: install-archive-sa_IN/UTF-8] Error 1
locale 'ar_BH.iso88596' already exists
cannot extend locale archive file
```

Maybe we actually want to apply pull request #616.

**Comment by tuliom** [comment]
This is the kind of issue fixed with PR #616 .

**Comment by tuliom** [comment]
I'm restarting AT next RHEL7 ppc64le build...

**Comment by gftg85** [comment]
The rebuild succeeded.

**Pull request merged**
