### PR TITLE
Remove flag to ignore warning on glibc

### PR DESCRIPTION
**Pull request by mscastanho**
The issue causing a maybe-uninitialized warning on glibc builds
on AT next has been fixed upstream by commit 9f8b135f76ac794.

We should not need to ignore this warning anymore to successfully
build AT next.

### CODE REVIEW

**Comment by mscastanho** [comment]
Actually, this should only be merged once glibc is updated to revision 9f8b135f76ac794 or newer on AT next.

**Comment by er-1** [comment]
> Actually, this should only be merged once glibc is updated to revision 9f8b135f76ac794 or newer on AT next.

I think you can update the revision in your patch.

**Comment by mscastanho** [comment]
Done.

**Comment by mscastanho** [comment]
Just rebased against the current master. I kept the update to glibc sources as the recent update still did not include `9f8b135f76ac794`.

**Pull request merged**
