### PR TITLE
Fix HTML syntax and tags

### PR DESCRIPTION
**Pull request by er-1**
Fix HTML syntax and tags to get rid of errors reported by `tidy`.

Signed-off-by: Erwan Prioul <erwan@linux.ibm.com>

### CODE REVIEW

**Comment by gftg85** [comment]
@er-1,

In #649, there's a mention do a configuration file (`docs/tidy.cfg`), but the file is not in the repository.  Do you have access to it?  Without it, I can't run `tidy` as reported in the bug, thus I can't verify that it actually fixes #649.

**Comment by er-1** [comment]
@gftg85,
Good catch.
My fix is based on running `tidy` without this configuration file `docs/tidy.cfg`. I agree it might not report the same errors/warnings.

**Comment by gftg85** [comment]
OK.

Your fixes look good to me, but the statement `Fix #649`, in the pull request message, would automatically close the bug.

Could you commit it directly (i.e.: not using the github.com interface), please?

**Comment by er-1** [comment]
@gftg85 
I removed the statement `Fix #649`, as we can't ensure this PR fixes the related issue (due to missing `docs/tidy.cfg`).

**Comment by gftg85** [comment]
Good, now you can safely merge using the github.com interface.  Thanks.

**Pull request merged**
